export const BALANCE = {
  debug: { godModeDefault: false, panelDefaultOpen: true, respawnKey: 'F2', godModeKey: 'F3', debugPanelKey: 'F4', respawnPosition: { x: -120, y: 1.75, z: 2 }, respawnHunger: 82, respawnThirst: 82 },
  interaction: { range: 3.4, highlightRange: 3.6, dropDistance: 1.85 },
  inventoryConfig: { baseCapacity: 10, hotbarSlots: 5 },
  viewModel: { defaultScale: 1.15, sway: 0.022, sprintLowering: 0.08 },
  models: { zombieVariations: 5, itemSpinSpeed: 0.55 },
  world: { halfSize: 180, playerBounds: 174, houseCount: 8, treeCount: 180, abandonedVehicleCount: 18, fenceSegmentLength: 7 },
  vitals: { hungerLossPerMinute: 1.05, thirstLossPerMinute: 1.75, starvationDamagePerSecond: 1.35, bleedingDamagePerSecond: 1.05, infectionGrowthPerSecond: 0.18, severeInfectionDamagePerSecond: 0.65, sprintStaminaPerSecond: 18, walkStaminaRegenPerSecond: 9, sneakStaminaRegenPerSecond: 12, jumpStaminaCost: 8, meleeStaminaCost: 6, wetnessRainGainPerSecond: 1.25, wetnessDryPerSecond: 0.22, temperatureLossRainWetness: 0.018, temperatureLossNight: 0.012, coldHpDamagePerSecond: 0.55, coldStaminaDrainPerSecond: 1.2, painStaminaRegenPenalty: 0.45, illnessStaminaPenalty: 0.25, unconsciousTemperature: 32.5, fractureSprintPenalty: 0.5 },
  clothing: { warmthToTemperatureProtection: 0.03, rainProtectionToWetnessReduction: 0.008, ruinedEffectMultiplier: 0, badlyDamagedEffectMultiplier: 0.35, damagedEffectMultiplier: 0.55, wornEffectMultiplier: 0.75, goodEffectMultiplier: 0.92, newEffectMultiplier: 1 },
  disease: { zombieInfectionChance: 0.12, untreatedBleedInfectionChancePerSecond: 0.002, spoiledFoodIllnessChance: 0.34, dirtyWaterIllnessChance: 0.3, dirtyRagInfectionChance: 0.2, antibioticsRelief: 34, disinfectantRelief: 20, painkillerRelief: 36 },
  zombie: { baseDamage: 19, bleedChance: 0.28, daySightRange: 18, nightSightRange: 24, alertedSightBonus: 6, hearingMultiplier: 1, wanderSpeed: 0.62, investigateSpeed: 1.45, chaseSpeed: 2.35, nightChaseSpeedBonus: 0.22, attackRange: 1.55, attackCooldownSeconds: 1.25, loseSightSeconds: 4.5, searchSeconds: 4, respawnSeconds: 480, barricadeDamage: 8 },
  loot: { globalChanceMultiplier: 0.82, respawnDelaySeconds: 900, containerRespawnSeconds: 3600, highValueRespawnSeconds: 7200, debugRespawnKey: 'F10' },
  weapons: { fallbackMeleeDamage: 12, fallbackMeleeRange: 1.7, fallbackMeleeNoiseRadius: 3, fallbackMeleeFireRate: 62, pistolShotNoiseRadius: 42, rifleShotNoiseRadius: 62, conditionLossMelee: 1.6, conditionLossShot: 0.8, malfunctionConditionMultiplier: 0.28 },
  access: { houseBreakSeconds: 3, interiorBreakSeconds: 2, metalBreakSeconds: 6, policeBreakSeconds: 7, militaryBreakSeconds: 10, doorBreakNoiseRadius: 32, metalDoorNoiseRadius: 48, lockpickSeconds: 4, lockpickSuccessChance: 0.62, lockpickBreakChance: 0.24, keyNoiseRadius: 2, containerSearchSeconds: 2.5, lockedContainerBreakSeconds: 5, containerBreakNoiseRadius: 22, alarmDurationSeconds: 55, alarmNoiseRadius: 82 },
  storage: { storageBoxCapacity: 34, vehicleTrunkCapacity: 18, groundPackCapacity: 12 },
  building: { woodWallHp: 180, woodGateHp: 150, barricadeHp: 95, storageBoxHp: 120, fenceSegmentHp: 115, sleepingBagHp: 60, placementDistance: 3.5, buildSeconds: 4, buildNoiseRadius: 12, costs: { wood_wall: { firewood: 3, nails: 2, hammer: 1 }, wood_gate: { firewood: 4, nails: 3, rope: 1, hammer: 1 }, barricade: { firewood: 2, nails: 1, hammer: 1 }, storage_box: { firewood: 2, nails: 2, hammer: 1 }, fence_segment: { firewood: 2, nails: 1, rope: 1, hammer: 1 }, sleeping_bag: { rag: 4, rope: 1 } } },
  events: { spawnCheckSeconds: 120, spawnChance: 0.25, maxActiveEvents: 2, eventDurationSeconds: 900, eventLootMultiplier: 1.3, signalRadius: 80 },
  horde: { initialSize: 9, maxHordes: 1, spawnIntervalSeconds: 420, hearingRadius: 115, moveSpeed: 0.55, nightSpeedBonus: 0.2, wanderRadius: 140 },
  repair: { sewingKitAmount: 34, ductTapeAmount: 20, toolboxAmount: 28, weaponCleaningAmount: 32, ruinedRepairAllowed: false },
  crafting: { defaultTimeSeconds: 3, ragTimeSeconds: 2, bandageTimeSeconds: 3, torchTimeSeconds: 4, campfireTimeSeconds: 5, backpackTimeSeconds: 7, spearTimeSeconds: 5, repairTimeSeconds: 4, boilWaterPreparedTimeSeconds: 5 },
  fire: { burnDurationSeconds: 300, warmthRadius: 8, warmthPerSecond: 0.08, lightIntensity: 1.25, noiseRadius: 5 },
  weight: { comfortableKg: 18, heavyKg: 32, staminaDrainHeavyMultiplier: 1.45, staminaRegenHeavyMultiplier: 0.62, sprintSpeedHeavyMultiplier: 0.82 },
  sound: { sneakNoiseRadius: 2.2, walkNoiseRadius: 7, sprintNoiseRadius: 18, jumpNoiseRadius: 12, inventoryNoiseRadius: 1.5, pickupNoiseRadius: 2.5, eatDrinkNoiseRadius: 2, reloadNoiseRadius: 8, painNoiseRadius: 10 },
  dayNight: { dayLengthSeconds: 900, startTime: 8.25, nightStartHour: 20, nightEndHour: 5.5 },
  weather: { changeCheckSeconds: 90, changeChance: 0.28, fogFarClear: 150, fogFarCloudy: 125, fogFarRain: 92, fogFarFog: 58, clearTemperature: 16, cloudyTemperature: 12, rainTemperature: 8, fogTemperature: 6, nightTemperaturePenalty: -6 }
} as const;
