import { useEffect, useState } from 'react';
import GameCanvas from './game/GameCanvas';
import type { EquipmentSlot, GridItemView, HudState, InventoryEntry } from './game/types';

const emptyClothing = { head: 'leer', torso: 'leer', legs: 'leer', feet: 'leer', hands: 'leer', vest: 'leer', backpack: 'leer' };
const emptyGrid = { cols: 5, rows: 4, usedCells: 0, freeCells: 20, items: [], equipment: {}, validationOk: true, validationErrors: [] };
const initialHud: HudState = {
  hp: 100, stamina: 100, hunger: 88, thirst: 84, bleeding: false, infection: 0, infected: false, bodyTemperature: 37, wetness: 0, cold: 0, illness: 0, sick: false, pain: 0, unconscious: false, fracture: false,
  capacity: 20, usedSlots: 0, totalWeight: 0, armor: 0, warmth: 0, rainProtection: 0, weapon: 'Fäuste', weaponCondition: '-', ammo: 0, ammoText: 'Nahkampf', currentBackpack: 'Kein Rucksack', currentArmor: 'Keine Rüstung', clothing: emptyClothing,
  zombiesAlerted: 0, interactionPrompt: '', message: 'Klicke auf Start und danach ins Spiel, um die Maus zu sperren.', warning: '', inventoryOpen: false, craftingOpen: false, craftingRecipes: [], inventory: [], gridInventory: emptyGrid, selectedItemId: null, hotbar: [], debug: { godMode: false, debugPanelOpen: true, playerPosition: '-', zombieCount: 0, lootSpotCount: 0, droppedItemCount: 0 },
  timeText: '08:15', weather: 'cloudy', noiseLevel: 'leise', actionLabel: '', actionProgress: 0, nearbyFireWarmth: 0, damageFlash: 0,
  worldPrompt: '', locationName: 'Wildnis', eventHint: '', compassHeading: '-', mapOpen: false, buildMode: false, selectedBuildable: 'Barrikade', storageOpen: false, storageTitle: '', storageUsed: 0, storageCapacity: 0, storageItems: []
};
const weatherLabels = { clear: 'klar', cloudy: 'bewölkt', rain: 'Regen', fog: 'Nebel' };
const slotLabels: Partial<Record<EquipmentSlot, string>> = { primary: 'Primär', secondary: 'Sekundär', melee: 'Nahkampf', head: 'Kopf', face: 'Maske', torso: 'Oberkörper', vest: 'Weste', hands: 'Hände', legs: 'Beine', feet: 'Schuhe', backpack: 'Rucksack' };
const equipmentSlots: EquipmentSlot[] = ['primary', 'secondary', 'melee', 'head', 'face', 'torso', 'vest', 'hands', 'legs', 'feet', 'backpack'];
function sendKey(code: string) { window.dispatchEvent(new KeyboardEvent('keydown', { code })); }
function inventoryAction(type: string, itemId?: string, extra: Record<string, unknown> = {}) { window.dispatchEvent(new CustomEvent('dayx-inventory-action', { detail: { type, itemId, ...extra } })); }
function categoryLabel(entry: InventoryEntry) { return `${entry.type} · ${entry.conditionLabel} · ${entry.totalWeight} kg`; }
function itemDetails(entry?: GridItemView | InventoryEntry | null) { if (!entry) return null; return <div className="item-details"><h3>{entry.name}</h3><p>{categoryLabel(entry)}</p><p>{entry.description}</p>{'w' in entry ? <p>Größe: {entry.w}x{entry.h} · Stack: {entry.count}/{entry.maxStack} · Rotation: {entry.rotated ? 'gedreht' : 'normal'}</p> : null}<div className="action-buttons"><button onClick={() => inventoryAction('use', entry.instanceId ?? entry.id)}>Benutzen</button><button onClick={() => inventoryAction('equip', entry.instanceId ?? entry.id)}>Ausrüsten</button><button onClick={() => inventoryAction('split', entry.instanceId ?? entry.id)}>Stack teilen</button><button onClick={() => inventoryAction('rotate', entry.instanceId ?? entry.id)}>Rotieren</button><button onClick={() => inventoryAction('drop', entry.instanceId ?? entry.id)}>Drop</button><button onClick={() => inventoryAction('delete', entry.instanceId ?? entry.id)}>Wegwerfen</button></div></div>; }

export default function App() {
  const [started, setStarted] = useState(false);
  const [hud, setHud] = useState<HudState>(initialHud);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [drag, setDrag] = useState<{ id: string; rotated: boolean } | null>(null);
  const [context, setContext] = useState<{ item: GridItemView; x: number; y: number } | null>(null);
  const grid = hud.gridInventory ?? emptyGrid;
  const selectedItem = grid.items.find((entry) => entry.instanceId === selectedId) ?? Object.values(grid.equipment).find((entry) => entry?.instanceId === selectedId) ?? grid.items[0] ?? null;

  useEffect(() => {
    const onKey = (event: KeyboardEvent) => { if (!drag) return; if (event.code === 'KeyR') { event.preventDefault(); setDrag((current) => current ? { ...current, rotated: !current.rotated } : current); } };
    window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey);
  }, [drag]);

  if (!started) return <main className="menu-screen"><section className="menu-panel"><p className="eyebrow">Hardcore Survival FPS Prototype</p><h1>Day-X</h1><p>Grid-Inventar mit Itemgrößen, Drag-and-Drop, Rotation, Stacks, Ausrüstung, Hotbar und Welt-Drops.</p><div className="menu-grid"><span>Grid</span><span>Drag & Drop</span><span>Rotation</span><span>Stacks</span><span>Equipment</span><span>Hotbar</span></div><button onClick={() => setStarted(true)}>Prototyp starten</button><small>Tab/I Inventar · R beim Ziehen rotiert · Rechtsklick Kontextmenü · F2 Respawn · F3 God Mode</small></section></main>;

  const onDropCell = (x: number, y: number) => { if (!drag) return; inventoryAction('grid_move', drag.id, { x, y, rotated: drag.rotated }); setDrag(null); };
  const onDropEquipment = (slot: EquipmentSlot) => { if (!drag) return; inventoryAction('equip_slot', drag.id, { slot }); setDrag(null); };
  const onDropHotbar = (slot: number) => { if (!drag) return; inventoryAction('hotbar', drag.id, { slot }); setDrag(null); };

  return <main className="game-screen" onClick={() => context && setContext(null)}><GameCanvas onHudChange={setHud} /><section className="hud"><div className="meta-row"><span>Ort: {hud.locationName}</span><span>Kompass: {hud.compassHeading}</span><span>Zeit: {hud.timeText}</span><span>Wetter: {weatherLabels[hud.weather]}</span><span>Geräusch: {hud.noiseLevel}</span></div><div className="stat"><span>HP</span><meter min="0" max="100" value={hud.hp} /><b>{hud.hp}</b></div><div className="stat"><span>Ausdauer</span><meter min="0" max="100" value={hud.stamina} /><b>{hud.stamina}</b></div><div className="stat"><span>Hunger</span><meter min="0" max="100" value={hud.hunger} /><b>{hud.hunger}</b></div><div className="stat"><span>Durst</span><meter min="0" max="100" value={hud.thirst} /><b>{hud.thirst}</b></div><div className="quick-row"><span>Inventar: {grid.usedCells}/{grid.cols * grid.rows}</span><span>Gewicht: {hud.totalWeight} kg</span><span>Waffe: {hud.weapon}</span><span>Munition: {hud.ammoText}</span><span>Zombies: {hud.zombiesAlerted}</span></div><div className="hotbar">{hud.hotbar.map((slot) => <button key={slot.slot} onDragOver={(e) => e.preventDefault()} onDrop={() => onDropHotbar(slot.slot)} onClick={() => sendKey(`Digit${slot.slot}`)} className={slot.instanceId && slot.instanceId === hud.selectedItemId ? 'active' : ''}><b>{slot.slot}</b><span>{slot.label}</span></button>)}</div>{hud.worldPrompt ? <p className="interaction">{hud.worldPrompt}</p> : null}{hud.interactionPrompt ? <p className="interaction">{hud.interactionPrompt}</p> : null}{hud.warning ? <p className="warning">{hud.warning}</p> : null}{hud.actionLabel ? <div className="action-box"><span>{hud.actionLabel}</span><progress max="1" value={hud.actionProgress} /></div> : null}<p className="message">{hud.message}</p></section>

  {hud.debug.debugPanelOpen && <aside className="debug-panel"><h2>Debug</h2><button onClick={() => sendKey('F2')}>Respawn</button><button onClick={() => sendKey('F3')}>{hud.debug.godMode ? 'God Mode AUS' : 'God Mode AN'}</button><button onClick={() => inventoryAction('debug_add_items')}>Testitems</button><button onClick={() => inventoryAction('debug_validate')}>Grid prüfen</button><button onClick={() => inventoryAction('debug_clear')}>Inventar leeren</button><p>God Mode: <b>{hud.debug.godMode ? 'AKTIV' : 'aus'}</b></p><p>Position: {hud.debug.playerPosition}</p><p>Zombies: {hud.debug.zombieCount}</p><p>Lootspots: {hud.debug.lootSpotCount}</p><p>Grid: {grid.freeCells} frei / {grid.usedCells} belegt</p></aside>}

  {hud.inventoryOpen && <aside className="grid-inventory"><header><h2>Grid-Inventar</h2><p>{grid.cols}x{grid.rows} · {grid.validationOk ? 'Grid OK' : `Fehler: ${grid.validationErrors[0]}`}</p></header><section className="inventory-layout"><div><h3>Raster</h3><div className="inventory-grid" style={{ gridTemplateColumns: `repeat(${grid.cols}, 42px)`, gridTemplateRows: `repeat(${grid.rows}, 42px)` }}>{Array.from({ length: grid.cols * grid.rows }).map((_, index) => { const x = index % grid.cols; const y = Math.floor(index / grid.cols); return <div key={`${x}-${y}`} className="grid-cell" onDragOver={(e) => e.preventDefault()} onDrop={() => onDropCell(x, y)} />; })}{grid.items.map((item) => <div key={item.instanceId} draggable onDragStart={() => setDrag({ id: item.instanceId, rotated: item.rotated })} onDragEnd={() => setDrag(null)} onClick={(e) => { e.stopPropagation(); setSelectedId(item.instanceId); }} onContextMenu={(e) => { e.preventDefault(); setContext({ item, x: e.clientX, y: e.clientY }); }} className={`grid-item ${selectedId === item.instanceId ? 'selected' : ''}`} style={{ gridColumn: `${item.x + 1} / span ${item.w}`, gridRow: `${item.y + 1} / span ${item.h}` }}><strong>{item.name}</strong><span>{item.count > 1 ? `x${item.count}` : `${item.w}x${item.h}`}</span></div>)}</div><p className="inventory-help">Ziehe Items auf freie Zellen. Während des Ziehens dreht R das Item. Ungültige Drops werden vom System abgelehnt.</p></div><div><h3>Ausrüstung</h3><div className="equipment-slots">{equipmentSlots.map((slot) => { const item = grid.equipment[slot] ?? null; return <div key={slot} className="equipment-slot" onDragOver={(e) => e.preventDefault()} onDrop={() => onDropEquipment(slot)}><small>{slotLabels[slot] ?? slot}</small>{item ? <button draggable onDragStart={() => setDrag({ id: item.instanceId, rotated: item.rotated })} onClick={() => setSelectedId(item.instanceId)}>{item.name}</button> : <span>leer</span>}</div>; })}</div><h3>Details</h3>{itemDetails(selectedItem)}</div></section></aside>}

  {context && <div className="context-menu" style={{ left: context.x, top: context.y }} onClick={(e) => e.stopPropagation()}><button onClick={() => inventoryAction('use', context.item.instanceId)}>Benutzen</button><button onClick={() => inventoryAction('equip', context.item.instanceId)}>Ausrüsten</button><button onClick={() => inventoryAction('split', context.item.instanceId)}>Stack teilen</button><button onClick={() => inventoryAction('rotate', context.item.instanceId)}>Rotieren</button><button onClick={() => inventoryAction('drop', context.item.instanceId)}>Drop</button><button onClick={() => inventoryAction('delete', context.item.instanceId)}>Wegwerfen</button></div>}
  {hud.craftingOpen && <aside className="crafting-panel"><h2>Crafting</h2><ol start={4}>{hud.craftingRecipes.map((recipe) => <li key={recipe.id} className={recipe.available ? 'available' : 'missing'}><strong>{recipe.name}</strong><small>{recipe.timeSeconds}s {recipe.available ? 'bereit' : `fehlt: ${recipe.missing.join(', ')}`}</small></li>)}</ol></aside>}
  {hud.storageOpen && <aside className="storage-panel"><h2>{hud.storageTitle}</h2><p>Kapazität: {hud.storageUsed}/{hud.storageCapacity}</p><ul>{hud.storageItems.map((entry) => <li key={entry.id}><strong>{entry.name}</strong><span>x{entry.count}</span></li>)}</ul></aside>}
  <div className="crosshair" />{hud.damageFlash > 0 ? <div className="damage-flash" style={{ opacity: Math.min(0.45, hud.damageFlash * 0.45) }} /> : null}</main>;
}
